travis:
  secure:
    BINSTAR_TOKEN: HEr/OeYnQf0tU0+hrGaT6jBsn/nTQYtRas+BSxOyV6KwPhi8PW03ZId7+fHZU3Qp476HK2vb1UcoMkNAIRbkjtv4Rmu6k2XJZif8SAVrHQ51WYYBEj3GlmINyKC6robmQDugTXCqRRsM+JIqeFWWuk91DjVfgt+ebVF9jn3CWoer466V5slzAyxYLpVZqNVSlIF4rifUWRhkDEIe6rr5erEqBvbEfv3jjEAxCSwPw9QjsKidsusRdKR3zz3cly1iDcxa9XgVoOk1/ZBG3abC8F4WTuQsEAtesF//0NQThy0FXluFKO2YVIpQyvA5bBFXTcFzaWHM0lIXALARlUdF9RwpkbfJhzv0VHmWpeKT7WRDMJ/BePTVFnGJyWEsi5Xd/J+/lnJtv4d0pvMgBiSnAVL/URi/8d7hbepMb+UUnleO0ACEZb3Tmr83P3ZiiElQBhB5jFIbqwnvmz0LuRmuU8ebyzqgBWdWhVFuxQSZlRAq+w7KtE9RJVHhr00ZNAeDP2kNGnJtOUEoqWsSyriKzvKJHvu1qS8oSV88R5TsK5u39nLbDZUKb2hgn6iPGY3HtHXhuT52GXQHw4TD++7gZsUy7JugNM/+pOlWzgR3PbYvcWxbHS8kycZ3FaHROcZfAGgwKLKIka0YzcdyT24uRoXcysR8TqXBUbkcPIZ5wNY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
