travis:
  secure:
    BINSTAR_TOKEN: wOEv4oYgzzqROt7UnQm9cM2FT1QjaPmwqPEidaj30/i+OfbncmFgMJAnOn9Aq4slTiB8/LR4/BtZ6odydsQQFp1ohOvhmT6hdag16e9eyaKoapiqsoGv6ptz6FuLRZBtPWqVtgBtc8bQ/x1epoBtKpc4wW373ZcJtlDLQFMFizhL/m3D9RSJzTZzoIiXzucw+NyhXG33gCA39sIL71FpHJ+v/HLdm+v/jQLE0U9pQY6hGq/FHSdfCNE3v3UHKMqfeM9oNty6wKovovUESHE9mo7SBvh1C9u3/bfSUjZMWCV6aaUfFWe2J23iyIi3CLESbC6rAkVY2D3xtW4LC5LgS2qhzxt/C3GEN3ptcvozYhZY7MyI4USJf9emDdXungmfkC3wpX4HRwS2or0K5NQly3yoX4kderyV9MOmbntUqeukxpN0zgsGYrIalKqB1eYh7MVJal4o4bksUoFCyXdo9r8b0QViLVaN0nQYMb0nNRhuaqGMUyQVbXhjWsrWrUERS6GzUtccq+fJtIrnb9l0Hg28nnK6e4JqP3HnIQxSPp+tjbJYhseTXBDU4uy/+UfHnGJoiAQlr3nwU4qVyRs7e+pWbTrSGnikY5NkMyCI/BR4/MwnWOrDkxp6X38oYbyJTU6bv4t1xa0fkb+BtxAlXFnVAtN48aC5T65PQyENnHc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
